This is makeindex, version 2.15 [MiKTeX 2.9.6300 64-bit] (kpathsea + Thai support).
Scanning style file ./enddoku.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file enddoku.acn....done (3 entries accepted, 0 rejected).
Sorting entries....done (5 comparisons).
Generating output file enddoku.acr....done (9 lines written, 0 warnings).
Output written in enddoku.acr.
Transcript written in enddoku.alg.
